version: '3'

services:
  mssql-adventure:
    image: mssql-adventure
    build: .
    ports:
      - '1433:1433'
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      MSSQL_SA_PASSWORD: 'teste@123'

volumes:
  mssql-data:
